project_id = "xjmuxtoichwikoquishz"

[functions.processar-documento]
verify_jwt = false

[functions.processar-conta-luz]
verify_jwt = false

[functions.criar-proposta]
verify_jwt = false

[functions.registrar-visualizacao]
verify_jwt = false

[functions.notificar-email]
verify_jwt = false

[functions.cleanup-debug-files]
verify_jwt = false