// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjmuxtoichwikoquishz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbXV4dG9pY2h3aWtvcXVpc2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTQxMzcsImV4cCI6MjA2NzgzMDEzN30.mPYN1QeAi59Ze1H2SeGxrSWzK4mTtS44XMtQqRcPzJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});